[workspace]
members = [".", "./ub_parser"]

[package]
name = "ub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ub_parser = { path = "./ub_parser" }